-- drop index idx_user_id_at_dismissed_feature_callouts;
-- drop index idx_created_at_utc_posts;
-- drop index idx_user_id_and_created_at_utc;
-- drop table dismissed_feature_callouts;
-- drop index users_geog_idx;
-- drop table posts;
-- drop table users;

create table if not exists users
(
    "userId" bigint not null,
    "menuId" int,
    "username" text,
    "firstName" text,
    "lastName" text,
	"lon" double precision,
    "lat" double precision,
	"geog" geography(POINT, 4326),
	"languageCode" text,
	"reportCnt" int default(0),
	"shadowBanned" boolean default(false),
	"createdAtUtc" timestamp without time zone not null default (now() at time zone 'utc'),

    primary key ("userId")
);

create index if not exists users_geog_idx on users using gist(geog);

create table if not exists posts
(
    "postId" bigint generated by default as identity primary key,
    "userId" bigint not null references "users" ("userId"),
    "text" text,
	"lon" double precision,
    "lat" double precision,
	"geog" geography(POINT, 4326),
	"reportCnt" int default(0),
	"createdAtUtc" timestamp without time zone not null default (now() at time zone 'utc')
);

create index if not exists idx_created_at_utc_posts on "posts"("createdAtUtc");
create index if not exists idx_user_id_and_created_at_utc on "posts"("userId", "createdAtUtc");

create table if not exists dismissed_feature_callouts (
    "id" bigint generated by default as identity primary key,
	"userId" bigint not null, -- do not reference to users table, so it can be used when user isn't present
	"featureName" text not null,
	"createdAtUtc" timestamp without time zone not null default (now() at time zone 'utc'),
	unique ("userId","featureName")
);

create index if not exists idx_user_id_at_dismissed_feature_callouts on "dismissed_feature_callouts"("userId");
